### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by phamdin** [Uconnect-Technologies/wertik-js#146]
**Is your feature request related to a problem? Please describe.**
Please support MongoDB Support.

**Describe the solution you'd like**
Mongoose js

**Describe alternatives you've considered**
Nothing.

**Additional context**
Please allow using MongoDB.

**Comment by ilyaskarim** [comment]
@phamdin Wertik js now supports Mongo DB.

**Comment by ilyaskarim** [comment]
Closing the issue now.
