### ISSUE TITLE
Allow storage feature

### ISSUE THREAD

**Issue by phamdin** [Uconnect-Technologies/wertik-js#148]
**Is your feature request related to a problem? Please describe.**
Allow uploading feature. Uploading should be done from atleast:

1. Rest Api
2. GraphQL.

**Describe the solution you'd like**
Use multer-js to upload documents.

**Describe alternatives you've considered**
formidable

**Comment by ilyaskarim** [comment]
The default storage feature is done, You can view, list and upload files, Please see [c1fa819](https://github.com/Uconnect-Technologies/wertik-js/commit/c1fa81944ab8e2751e6195b720042dd57f9dfa5f

**Comment by ilyaskarim** [comment]
Fixed in v1.8.3
