### ISSUE TITLE
Setup proper email in Wertik-js

### ISSUE THREAD

**Issue by phamdin** [Uconnect-Technologies/wertik-js#149]
**Is your feature request related to a problem? Please describe.**
Email feature is works with fake mailer, Please setup proper email in Wertik-js.

**Comment by ilyaskarim** [comment]
This issue is addressed in commit https://github.com/Uconnect-Technologies/wertik-js/issues/149. Will be merged with 1.8.3 milestone.

**Comment by ilyaskarim** [comment]
Fixed in v1.8.3
