### ISSUE TITLE
Sorting feature is missing from list feature

### ISSUE THREAD

**Issue by phamdin** [Uconnect-Technologies/wertik-js#153]
**Is your feature request related to a problem? Please describe.**
Sorting feature is missing from list feature

**Describe the solution you'd like**
Please add sorting feature to list.

**Comment by ilyaskarim** [comment]
@phamdin Please see https://github.com/Uconnect-Technologies/wertik-js/commit/b2e4ad8093aebc1b3a337132311a76c67e0fce47. The request is done and will be merged into 1.8.3 release.

**Comment by ilyaskarim** [comment]
Fixed in v1.8.3
