### ISSUE TITLE
Write Documentation

### ISSUE THREAD

**Issue by ilyaskarim** [Uconnect-Technologies/wertik-js#27]

**Comment by ilyaskarim** [comment]
I am closing this as I have created a board on Trello for this, here it is https://trello.com/b/mJB0xR2u/nodeboilerplate. This issue board is to capture bugs. 

Trello Board: https://trello.com/b/mJB0xR2u/nodeboilerplate.
Bug Report: https://github.com/ilyaskarim/NodeSaaSBoilerplate/issues/new.

**Comment by ilyaskarim** [comment]
Test

**Comment by ilyaskarim** [comment]
test

**Comment by ilyaskarim** [comment]
test

**Comment by ilyaskarim** [comment]
@sonicviz I hope you are doing great. You made a comment around 7-8 months ago, We have now our documentation now http://www.wapgee.com/wertik-js/.

**Comment by ilyaskarim** [comment]
@sonicviz You can also post a request on our first milestone: https://github.com/Uconnect-Technologies/wertik-js/milestone/1.

**Comment by sonicviz** [comment]
Thanks!
