### ISSUE TITLE
I have found a grammar mistake

### ISSUE THREAD

**Issue by massoGit-ma** [Uconnect-Technologies/wertik-js#339]
- I have found a grammatical mistake (! grammar mistake)
- "Why you should use wertik JS" part needs more quality description along with few corrections in punctuation.
- Right now there's nothing in wertik app right now.... Please remove " right now" from the beginning or from the end.
- wertik helps you set up servers (! setting up)

**Comment by ilyaskarim** [comment]
Hi @massoGit-ma, Thanks for the grammar mistakes, I will fix them, thank you so much.

**Comment by ilyaskarim** [comment]
@massoGit-ma I have fixed the issues and published the changes.

**Comment by massoGit-ma** [comment]
Now it's looking more elegant comparatively

**Comment by massoGit-ma** [comment]
@ilyaskarim now it's looking more elegant comparatively
