### ISSUE TITLE
Exposed mongodb credentials

### ISSUE THREAD

**Issue by eth0izzle** [Uconnect-Technologies/wertik-js#47]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@ds027719.mlab.com` in file [\examples\demo\index.js](https://github.com/ilyaskarim/wertik-js/blob/master\examples\demo\index.js)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by ilyaskarim** [comment]
@eth0izzle Thanks for the looking into it, yeah I am rewriting the library from scratch and I will consider your opinion on moving secrets to environment variables.

**Comment by ilyaskarim** [comment]
The risky data has been removed. Closing issue. thanks @eth0izzle .
