### ISSUE TITLE
How to send email?

### ISSUE THREAD

**Issue by amjadharri** [Uconnect-Technologies/wertik-js#58]
I was going through this library and Is there any function to send emails with templates option?

**Comment by ilyaskarim** [comment]
Now app sends two context varialbes called:

sendEmail
emailTemplates

**sendEmail** a function to sened emails.
**emailTemplates** contains all email templates in an Object to send emails.

See: 

https://github.com/ilyaskarim/wertik-js/blob/master/src/framework/graphql/index.ts#L24
https://github.com/ilyaskarim/wertik-js/blob/master/src/framework/graphql/index.ts#L25

**Comment by amjadharri** [comment]
juu
